//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebScraping
{
    using System;
    using System.Collections.Generic;
    
    public partial class Farmacia
    {
        public int id { get; set; }
        public string Empresa { get; set; }
        public string Endereco { get; set; }
        public string url { get; set; }
        public string classificacao { get; set; }
        public string latitude { get; set; }
        public string longitude { get; set; }
        public string categoria { get; set; }
        public string estado { get; set; }
        public string cidade { get; set; }
        public string cep { get; set; }
        public string ddd { get; set; }
        public string telefone { get; set; }
        public string site { get; set; }
        public string horario { get; set; }
    }
}
