//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebScraping
{
    using System;
    using System.Collections.Generic;
    
    public partial class LINKDOWNLOAD
    {
        public string serie { get; set; }
        public string link { get; set; }
        public decimal ID { get; set; }
        public string tipo { get; set; }
        public string shortlink { get; set; }
    }
}
