//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebScraping
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class SERIEEntities : DbContext
    {
        public SERIEEntities()
            : base("name=SERIEEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<IMDB> IMDB { get; set; }
        public virtual DbSet<LINKDOWNLOAD> LINKDOWNLOAD { get; set; }
        public virtual DbSet<SERIADO> SERIADO { get; set; }
    }
}
